import validator from 'validator'

import { UpdateUserUseCase } from '../use-cases/update-user.js'
import { EmailAlreadyInUseError } from '../errors/user.js'
import { badRequest, serverError, success } from './helper.js'

export class UpdateUserController {
  async execute(httpRequest) {
    try {
      const userId = httpRequest.params.userId
      const isIdValid = validator.isUUID(userId)

      if (!isIdValid) {
        return badRequest({
          message: 'The provided ID  is not valid',
        })
      }

      const updateUserParams = httpRequest.body

      const allowedFields = ['first_name', 'last_name', 'email', 'password']

      const someFieldIsNotAllowed = Object.keys(updateUserParams).some(
        (field) => !allowedFields.includes(field),
      )

      if (someFieldIsNotAllowed) {
        return badRequest({ message: 'Some provided field is not allowed' })
      }

      if (updateUserParams.password) {
        const passwordIsNotValid = updateUserParams.password.length < 6

        if (passwordIsNotValid) {
          return badRequest({
            message: 'Password must be at least 6 characters',
          })
        }
      }

      if (updateUserParams.email) {
        const emailIsValid = validator.isEmail(updateUserParams.email)

        if (!emailIsValid) {
          return badRequest({
            message: 'Invalid e-mail. Please provide a valid one.',
          })
        }
      }
      const updateUserUseCase = new UpdateUserUseCase()
      const updatedUser = await updateUserUseCase.execute(
        userId,
        updateUserParams,
      )

      return success(updatedUser)
    } catch (error) {
      if (error instanceof EmailAlreadyInUseError) {
        return badRequest({ message: error.message })
      }
      console.error(error)
      return serverError()
    }
  }
}
